### ISSUE TITLE
Getting a Contract to work with Hyperledger Fabric V2.2(or V2.1.1)

### ISSUE THREAD

**Issue by JohnGr001** [accordproject/hlf-cicero-contract#1]
I am trying to get this project to work with HLF V2.2 (or V2.1.1)

I have succeeded in loading the chaincode and initialising the chaincode. 

The README is not clear on how to then invoke the "instance" / trigger.

Happy to help refine the README so that it works with V2.2.

**Comment by dselman** [comment]
I've just tested the install on Fabric v2.3.1 and it worked fine for me.
