### ISSUE TITLE
[Question] Initializing a custom contract

### ISSUE THREAD

**Issue by Gonza116** [accordproject/hlf-cicero-contract#5]
I would like to try some self made cicero contracts using the test network. However, I don't really understand where the src inside the markdown contracts are pointing to. Is it the .cta or .cto contract, the .ergo logic, the state of the contract or something else? Is there a way to initialize locally stored contracts? Thanks in advance.

**Comment by dselman** [comment]
The markdown file references a CTA file (archive) from the Accord Project template library at https://templates.accordproject.org. The model, text and logic for the template are within the CTA file.

There's not currently a way in the sample chaincode to load and reference local CTA files - that would require changes to the chaincode. I will create a feature request issue for that.
